# Generated by Django 4.1.1 on 2022-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.TextField(default='undefined', verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='task',
            name='dateOfPublishing',
            field=models.DateField(default='2022-09-12', verbose_name='Дата публікації'),
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.TextField(default='undefined', verbose_name='Рівень складності'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(default='undefined', verbose_name='Текст завдання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='undefined', max_length=50, verbose_name='Назва'),
        ),
    ]
