# Generated by Django 4.1.1 on 2022-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_answer_task_dateofpublishing_task_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='undefined', max_length=100, verbose_name='Iм`я користувача')),
                ('age', models.BigIntegerField(default=0, max_length=3, verbose_name='Вік')),
                ('email', models.CharField(default='undefined', max_length=150, verbose_name='Email')),
                ('phone', models.CharField(default='undefined', max_length=15, verbose_name='Телефон')),
                ('HaveAuto', models.BooleanField(default=0, verbose_name='Має авто')),
            ],
        ),
    ]
